# Generated by Django 5.2.4 on 2025-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa_numero',
            field=models.CharField(blank=True, help_text='Número da mesa para pedidos de mesa', max_length=10),
        ),
    ]
