# Generated by Django 5.2.4 on 2025-07-18 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_mesa_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número da Mesa')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('reservada', 'Reservada')], default='aberta', max_length=20)),
                ('aberta_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aberta em')),
                ('fechada_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechada em')),
                ('total_consumido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Consumido')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável pela Mesa')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
    ]
