# Generated by Django 5.2.4 on 2025-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preparacao_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='saida_confirmada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
