# Generated by Django 5.2.4 on 2025-07-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_add_status_field'),
    ]

    operations = [
    ]
