# Generated by Django 5.2.4 on 2025-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_sync_timestamp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_cancelamento_hash', models.CharField(default='', help_text='Senha necessária para cancelar pedidos (armazenada com hash)', max_length=256)),
                ('permitir_cancelamento', models.BooleanField(default=True, help_text='Permite cancelamento de pedidos')),
                ('tempo_maximo_cancelamento', models.IntegerField(default=30, help_text='Tempo máximo em minutos para cancelar um pedido após criação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Pedidos',
                'verbose_name_plural': 'Configurações de Pedidos',
            },
        ),
    ]
