# Generated by Django 5.2.4 on 2025-07-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_pedido_status_pedido_cancelado_em_and_more'),
        ('pedidos', '0010_add_configuracao_pedido'),
    ]

    operations = [
    ]
