# Generated by Django 5.2.4 on 2025-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_merge_20250724_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comanda_impressa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('preparando', 'Preparando'), ('saindo', 'Saindo'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=20),
        ),
    ]
