# Generated by Django 5.2.4 on 2025-07-12 19:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='auto', help_text='Preferência de tema da interface', max_length=10, verbose_name='Tema')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificações ativadas')),
                ('language', models.CharField(default='pt-br', max_length=10, validators=[django.core.validators.RegexValidator(message='Formato deve ser: pt-br, en-us, etc.', regex='^[a-z]{2}-[a-z]{2}$')], verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência do Usuário',
                'verbose_name_plural': 'Preferências dos Usuários',
            },
        ),
    ]
