# Generated by Django 5.2.4 on 2025-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_disponivel',
            field=models.IntegerField(default=0, help_text='Quantidade em estoque (0 = sem controle)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes separados por vírgula', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço único para produtos sem variação de tamanho', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos_precos',
            field=models.JSONField(blank=True, help_text='JSON com tamanhos e preços para produtos com variações', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('bebida', 'Bebida'), ('borda', 'Borda Recheada'), ('sobremesa', 'Sobremesa'), ('acompanhamento', 'Acompanhamento'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
    ]
